export { adoptProject, AdoptionConflictError } from "./adoption/adoptProject.js";
export type { AdoptProjectOptions, AdoptProjectResult } from "./adoption/adoptProject.js";
export { detectProject } from "./adoption/detectProject.js";
export type { DetectedProject } from "./adoption/detectProject.js";
export { writeAdoptionReport } from "./adoption/writeAdoptionReport.js";
export { checkBrain } from "./brain/checkBrain.js";
export { checkDoctor } from "./doctor/checkDoctor.js";
export type { DoctorCheck, DoctorResult } from "./doctor/checkDoctor.js";
export { createValidationReport, issueMessage } from "./validation/results.js";
export type { ValidationIssue, ValidationReport, ValidationSeverity } from "./validation/results.js";
export { addInstalledBot, AvipackProjectRequiredError, BotNotEnabledError, BotNotInstalledError, canRunBot, disableBot, enableBot, getBotState, listBotsWithState, requireKnownBot, resolveKnownBot, runBot, UnknownBotError } from "./bots/botLifecycle.js";
export type { BotActionResult, BotState } from "./bots/botLifecycle.js";
export { canWriteBotReport, isAllowedAvipackWritePath } from "./bots/botPermissions.js";
export { createBrain, deriveProjectName, TemplateConflictError } from "./brain/createBrain.js";
export { isAvipackProject, loadConfig, normalizeConfig, writeConfig } from "./config/loadConfig.js";
export type { AvipackConfig, BrainCheckResult } from "./config/types.js";
export { findKnownBot, listKnownBots } from "./plugins/botRegistry.js";
export type { BotManifest, BotPermissions } from "./plugins/botManifest.js";
export { copyTemplate } from "./templates/copyTemplate.js";
export { resolveTemplatePath } from "./templates/resolveTemplatePath.js";
export { updateGeneratedProjectMetadata } from "./templates/updateGeneratedProjectMetadata.js";
export { listStarterTemplates } from "./templates/templateRegistry.js";
export type { StarterTemplate } from "./templates/templateRegistry.js";
export { createAdr } from "./records/adrs.js";
export type { CreateAdrOptions, CreateAdrResult } from "./records/adrs.js";
export { createChangeRequest } from "./records/changeRequests.js";
export type { CreateChangeRequestOptions, CreateChangeRequestResult } from "./records/changeRequests.js";
export { getHighestRecordNumber, getNextRecordPath, slugifyTitle } from "./records/numberedRecords.js";
export { validateYaml } from "./validators/validateYaml.js";
