export { adoptProject, AdoptionConflictError } from "./adoption/adoptProject.js";
export type { AdoptProjectOptions, AdoptProjectResult } from "./adoption/adoptProject.js";
export { detectProject } from "./adoption/detectProject.js";
export type { DetectedProject } from "./adoption/detectProject.js";
export { writeAdoptionReport } from "./adoption/writeAdoptionReport.js";
export { checkBrain } from "./brain/checkBrain.js";
export { createBrain, deriveProjectName, TemplateConflictError } from "./brain/createBrain.js";
export { loadConfig } from "./config/loadConfig.js";
export type { AvipackConfig, BrainCheckResult } from "./config/types.js";
export { findKnownBot, listKnownBots } from "./plugins/botRegistry.js";
export type { BotManifest, BotPermissions } from "./plugins/botManifest.js";
export { copyTemplate } from "./templates/copyTemplate.js";
export { resolveTemplatePath } from "./templates/resolveTemplatePath.js";
export { updateGeneratedProjectMetadata } from "./templates/updateGeneratedProjectMetadata.js";
export { listStarterTemplates } from "./templates/templateRegistry.js";
export type { StarterTemplate } from "./templates/templateRegistry.js";
export { validateYaml } from "./validators/validateYaml.js";
